services:

  kafka:
    image: 'apache/kafka:3.9.0'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      # KRaft mode configuration
      KAFKA_NODE_ID: '1'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      # Topic configuration
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
      # Log directory
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - dev-kafka-data:/var/lib/kafka/data
    networks:
      - dev-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "0.0.0.0:9092", "--list" ]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s

  cassandra:
    image: 'cassandra:5.0.3'
    container_name: 'cassandra'
    environment:
      - 'CASSANDRA_DC=dc1'
      - 'CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch'
      - 'CASSANDRA_CLUSTER_NAME=dev'
    ports:
      - '9042:9042'
    volumes:
      - dev-cassandra-data:/var/lib/cassandra
    networks:
      - dev-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces;" ]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  cassandra-init:
    image: 'python:3.9-slim-buster'
    container_name: 'cassandra-init'
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./config/cassandra-init-scripts:/scripts
    networks:
      - dev-network
    entrypoint:
      - sh
      - -c
      - |
        apt-get update && apt-get install -y netcat-openbsd;
        pip install cassandra-driver;
        while ! nc -zv cassandra 9042; do
          echo "Waiting for Cassandra to be available...";
          sleep 1;
        done;
        python3 /scripts/init_cassandra.py
    restart: no

  redis:
    image: 'redis:7.4.2'
    container_name: 'redis'
    ports:
      - '6379:6379'
    restart: unless-stopped
    volumes:
      - dev-redis-data:/data
    networks:
      - dev-network
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s

volumes:
  dev-kafka-data:
  dev-cassandra-data:
  dev-redis-data:

networks:
  dev-network: