services:

  loki:
    image: 'grafana/loki:3.1.2'
    container_name: 'loki'
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - observability-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3100/metrics" ]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 5s

  alloy:
    image: 'grafana/alloy:v1.6.1'
    container_name: 'alloy'
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ../logs/application.log:/var/log/application.log
    networks:
      - observability-network
    restart: unless-stopped
    depends_on:
      loki:
        condition: service_healthy

  grafana:
    image: 'grafana/grafana:11.5.1'
    container_name: 'grafana'
    ports:
      - '3000:3000'
    networks:
      - observability-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/health" ]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 5s

networks:
  observability-network: