server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: roi-project-planner
    static_configs:
      - targets:
          - localhost
        labels:
          job: roi-project-planner-logs
          __path__: /var/log/application.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: "'@timestamp'"
            message: message
            level: level
            service: service
      - timestamp:
          source: timestamp
          format: "RFC3339Nano"
      - labels:
          level:
          service: