global:
  scrape_interval: 15s
  evaluation_interval: 5s
  external_labels:
    monitor: 'dev'

scrape_configs:
  - job_name: 'roi-project-planner-metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.86.53:8080' ]