apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: roi-project-planner-dev
  labels:
    app: cassandra
spec:
  serviceName: cassandra
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      # Anti-affinity to spread brokers across nodes
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: [ "cassandra" ]
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 1800
      containers:
        - name: cassandra
          image: cassandra:5.0.3
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 9042
              name: cql
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh", "-c", "nodetool drain" ]
          env:
            - name: MAX_HEAP_SIZE
              value: "2048M"
            - name: HEAP_NEWSIZE
              value: "512M"
            - name: CASSANDRA_SEEDS
              value: "cassandra-0.cassandra.roi-project-planner-dev.svc.cluster.local"
            - name: CASSANDRA_CLUSTER_NAME
              value: "MyAppCluster"
            - name: CASSANDRA_DC
              value: "DC1"
            - name: CASSANDRA_RACK
              value: "Rack1"
            - name: CASSANDRA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cassandra-secrets
                  key: username
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra-secrets
                  key: password
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
          livenessProbe:
            tcpSocket:
              port: 9042
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 9042
            initialDelaySeconds: 60
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
        storageClassName: standard

---

apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: roi-project-planner-dev
  labels:
    app: cassandra
spec:
  clusterIP: None
  ports:
    - port: 9042
      name: cql
  selector:
    app: cassandra